AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  DebateIt API

  SAM Template for DebateIt API

Parameters:
  EnvironmentParameter:
    Type: String
  DatabaseSecretName:
    Type: String
  DatabaseNameParameter:
    Type: String
    Default: debateitdb
  LogLevel:
    Type: String
    Description: Log level for the api
    Default: INFO

Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for the Database
      GroupName: !Sub "debateit-db-sg-${EnvironmentParameter}"
      SecurityGroupEgress:
        - Description: Allow all outbound traffic
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - Description: Allow all access for now
          FromPort: 5432
          ToPort: 5432
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
      VpcId: vpc-00e45ef046f0114bd
  DebateItDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref DatabaseSecretName
      Description: RDS database auto-generated user password
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "debateitdbowner"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
  DebateItDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBName: !Ref DatabaseNameParameter
      DBInstanceIdentifier: !Sub "debateitdb-${EnvironmentParameter}"
      DBInstanceClass: "db.t3.micro"
      DBSubnetGroupName: public-subnet-group
      Engine: postgres
      MasterUsername: !Sub "{{resolve:secretsmanager:${DebateItDBSecret}::username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${DebateItDBSecret}::password}}"
      PubliclyAccessible: true
      SourceRegion: us-east-1
      VPCSecurityGroups: [!Ref DBSecurityGroup]
  DebateItDBSecretAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DebateItDBSecret
      TargetId: !Ref DebateItDB
      TargetType: AWS::RDS::DBInstance
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AutoVerifiedAttributes:
        - email
      EmailVerificationMessage: "Your verification code is {####}"
      EmailVerificationSubject: "Your verification code"
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      Schema:
        - Mutable: true
          Name: email
          Required: true
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      UsernameAttributes: email
      UsernameConfiguration:
        CaseSensitive: false
      UserPoolName: !Sub "debateit-user-pool-${EnvironmentParameter}"
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub "debateit-user-pool-client-${EnvironmentParameter}"
      RefreshTokenValidity: 30
      TokenValidityUnits:
        RefreshToken: days
    DependsOn:
      - UserPool
  AuthRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ""
            Effect: Deny
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: "sts:AssumeRoleWithWebIdentity"
      RoleName: !Sub "debateit-auth-role-${EnvironmentParameter}"
  UnauthRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ""
            Effect: Deny
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: "sts:AssumeRoleWithWebIdentity"
      RoleName: !Sub "debateit-unauth-role-${EnvironmentParameter}"
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !Sub
            - "cognito-idp.${region}.amazonaws.com/${client}"
            - region: !Ref "AWS::Region"
              client: !Ref UserPool
      IdentityPoolName: !Sub "debateit-identity-pool-${EnvironmentParameter}"
  IdentityPoolRoleMap:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        unauthenticated: !GetAtt UnauthRole.Arn
        authenticated: !GetAtt AuthRole.Arn
    DependsOn:
      - IdentityPool
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      TracingEnabled: true
      BinaryMediaTypes:
        - "*~1*"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
  ORMLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: orm-layer
      Description: SQLAlchemy models and utilities
      ContentUri: ./orm_layer/
      CompatibleRuntimes:
        - python3.9
      LicenseInfo: "MIT"
      RetentionPolicy: Retain
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "debateit-bucket-${EnvironmentParameter}"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - GET
            AllowedOrigins:
              - "*"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource:
              Fn::Sub: arn:aws:s3:::${S3Bucket}/debates/pictures/*
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures: [x86_64]
      CodeUri: api/app
      Environment:
        Variables:
          LOG_LEVEL: !Sub "${LogLevel}"
          DB_SECRET_NAME: !Ref DebateItDBSecret
          S3_BUCKET: !Ref S3Bucket
      Events:
        GetDebateList:
          Type: Api
          Properties:
            Path: /debate/list
            Method: get
            RestApiId: !Ref APIGateway
        CreateDebate:
          Type: Api
          Properties:
            Path: /debate
            Method: post
            RestApiId: !Ref APIGateway
        UploadDebatePicture:
          Type: Api
          Properties:
            Path: /debate/{debate_id}/file
            Method: put
            RestApiId: !Ref APIGateway
        CreateResponse:
          Type: Api
          Properties:
            Path: /response
            Method: post
            RestApiId: !Ref APIGateway
        Vote:
          Type: Api
          Properties:
            Path: /response/{response_id}/vote
            Method: post
            RestApiId: !Ref APIGateway
        GetDebate:
          Type: Api
          Properties:
            Path: /debate/{debate_id}/single
            Method: get
            RestApiId: !Ref APIGateway
        GetDebateCategories:
          Type: Api
          Properties:
            Path: /debate/category/list
            Method: get
            RestApiId: !Ref APIGateway
        HelloEvent:
          Type: Api
          Properties:
            Path: /health
            Method: get
            RestApiId: !Ref APIGateway
      Handler: src.handler.lambda_handler
      Layers:
        - !Ref ORMLayer
      Policies:
        - SecretsManagerReadWrite
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
      Runtime: python3.9
      Timeout: 30
      Tracing: Active
