DEBATE_CATEGORIES = [
    "Economic Policy",
    "Environmental Issues",
    "Privacy and Security",
    "Drug Policy",
    "Criminal Justice",
    "Education",
    "Social Media",
    "Sports and Activism",
    "Censorship",
    "Food and Agriculture",
    "Healthcare",
    "Space Exploration",
    "Voting and Elections",
    "Alcohol Policy",
    "Other",
]
